language: node_js

node_js:
  - 6

services:
  - postgresql

before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - psql -d travis_ci_test -c "create sequence public.province_id_seq increment 1 minvalue 1 maxvalue 9223372036854775807;" -U postgres
  - psql -d travis_ci_test -c "create table public.province(id integer not null default nextval('province_id_seq'), name character varying, code character varying, region character varying, macro_region character varying);" -U postgres
  - psql -d travis_ci_test -c "insert into province values(91, 'Sondrio', 'SO', 'Lombardia', 'Settentrionale');" -U postgres
  - psql -d travis_ci_test -c "insert into province values(70, 'Pesaro e Urbino', 'PU', 'Marche', 'Centrale');" -U postgres
  - psql -d travis_ci_test -c "create sequence public.weather_id_seq increment 1 minvalue 1 maxvalue 9223372036854775807;" -U postgres
  - psql -d travis_ci_test -c "create table public.weather(id integer not null default nextval('weather_id_seq'), date timestamp with time zone, temperature integer, cloudeness integer, humidity integer, province_id integer);" -U postgres

script:
  - npm run coverage
  - npm run codecov
  - npm run lint
